### ISSUE TITLE
If two portals are preset their data will merge

### ISSUE THREAD

**Issue by pacific707** [seedcode/fmxj#4]
I came across this error where I had 2 portals on the same layout.  The resulting nested portals appeared to have merged data.  I first thought it was copying the data over the array.  But after I made the field names unique in each portal I was able to discover that it just adds to the array of field names.  I am trying to figure out how to have it clear the list each time.

**Comment by JasonChrYoung** [comment]
That sounds right, and I'll take a look too.  I'll be perfectly honest, that our preferred technique is making table specific calls to dedicated layouts and then "stitching them together" with the nestObjects() function. It's a lot easier doing this with 2 JSON arrays then with the FMPXMLRESULT ;-)
Having said that, I want it working and will get in there soon.
Thanks again!

**Comment by pacific707** [comment]
just wanted to add that this is really sweet.  I appreciate it and am happy to contribute.

**Comment by pacific707** [comment]
I was thinking about the fact that FMPXMLRESULT doesn't let you know if the fields are in a portal or not.  Couldn't you use fmpresultset with findany just to get the metadata about the fields?  Then you can turn portal nesting on for the user and know if a field is in a portal or not etc?  Just an idea
